<!DOCTYPE html>
<html>
<body>

    <p>  Hello, today is <?php echo date('l, F jS, Y'); ?>. </p>
    
    <ul class="table-view">
  <li class="table-view-cell">
    <a class="navigate-right">
      Item 1
    </a>
  </li>
  <li class="table-view-cell">
    <a class="navigate-right">
      Item 2
    </a>
  </li>
  <li class="table-view-cell">
    <a class="navigate-right">
      Item 3
    </a>
  </li>
</ul>
    </body>
    </html>